steps:
  # 1. Install your project dependencies using npm
  - name: 'node:20'
    entrypoint: 'npm'
    dir: 'ponies'
    args: ['install', '--only=production']

  # 2. Build the container image using Google's built-in cloud buildpack
  - name: 'gcr.io/k8s-skaffold/pack'
    dir: 'ponies'
    args: [
      'build', 
      'us-central1-docker.pkg.dev/tiny-trotters-pony-parties/tiny-trotters-app/app:$SHORT_SHA',
      '--builder', 'gcr.io/buildpacks/builder:v1',
      '--env', 'GOOGLE_ENTRYPOINT="npm start"'
    ]

# Forces Google Cloud to use Cloud Logging Only and skip the bucket requirement
options:
  logging: CLOUD_LOGGING_ONLY
